### ISSUE TITLE
won't populate products

### ISSUE THREAD

**Issue by LebToki** [MooSell/Android#1]
Force closes 
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                      at java.io.StringReader.<init>(StringReader.java:50)
                      at com.google.gson.JsonParser.parse(JsonParser.java:45)

**Comment by MrKindSir** [comment]
Same issue...

**Comment by bitsnaps** [comment]
Same issue, looks like the code need some work, it still using `AsyncTask` I'm getting: woocommerce_api_authentication_error with tested valid api key.

**Comment by narayananiyer86** [comment]
Im getting the same issue.

**Comment by bitsnaps** [comment]
> Im getting the same issue.

I guess I fixed that by using the IP address instead of localhost on my machine, more improvement here:
https://github.com/bitsnaps/WooAndroid
